export default {
    OpenSansMedium: 'OpenSansMedium',
    OpenSansSemiCondensedMedium: 'OpenSansSemiCondensedMedium',
    OpenSansSemiCondensedExtraBold: 'OpenSansSemiCondensedExtraBold',
    OpenSansMediumItalic: 'OpenSansMediumItalic',
    OpenSansRegular: 'OpenSansRegular',
    OpenSansSemiCondensedSemiBold: 'OpenSansSemiCondensedSemiBold',
    OpenSansSemiCondensedMediumItalic: 'OpenSansSemiCondensedMediumItalic',
    OpenSansSemiCondensedSemiBoldItalic: 'OpenSansSemiCondensedSemiBoldItalic',
    OpenSansSemiCondensedBold: 'OpenSansSemiCondensedBold',
    OpenSansSemiCondensedLight: 'OpenSansSemiCondensedLight',
    OpenSansSemiCondensedExtraBoldItalic: 'OpenSansSemiCondensedExtraBoldItalic',
    OpenSansSemiCondensedRegular: 'OpenSansSemiCondensedRegular',
    OpenSansSemiCondensedItalic: 'OpenSansSemiCondensedItalic',
    OpenSansSemiCondensedBoldItalic: 'OpenSansSemiCondensedBoldItalic',
    OpenSansSemiCondensedLightItalic: 'OpenSansSemiCondensedLightItalic',
    OpenSansSemiBold: 'OpenSansSemiBold',
    OpenSansSemiBoldItalic: 'OpenSansSemiBoldItalic',
    OpenSansCondensedItalic: 'OpenSansCondensedItalic',
    OpenSansLight: 'OpenSansLight',
    OpenSansCondensedMedium: 'OpenSansCondensedMedium',
    OpenSansCondensedRegular: 'OpenSansCondensedRegular',
    OpenSansCondensedSemiBold: 'OpenSansCondensedSemiBold',
    OpenSansExtraBold: 'OpenSansExtraBold',
    OpenSansCondensedSemiBoldItalic: 'OpenSansCondensedSemiBoldItalic',
    OpenSansItalic: 'OpenSansItalic',
    OpenSansLightItalic: 'OpenSansLightItalic',
    OpenSansCondensedLight: 'OpenSansCondensedLight',
    OpenSansCondensedLightItalic: 'OpenSansCondensedLightItalic',
    OpenSansExtraBoldItalic: 'OpenSansExtraBoldItalic',
    OpenSansCondensedMediumItalic: 'OpenSansCondensedMediumItalic',

    Roboto: 'Roboto'
}
