/*
 * Copyright (c) 2023, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
/* eslint-disable @typescript-eslint/no-var-requires */
const sites = require('./sites.js')
const dw = require('./dw.js')

module.exports = {
    app: {
        // Customize how your 'site' and 'locale' are displayed in the url.
        url: {
            site: 'path',
            locale: 'path',
            showDefaults: true,
            interpretPlusSignAsSpace: false
        },
        // The default site for your app. This value will be used when a siteRef could not be determined from the url
        defaultSite: dw.SITE_ID,
        // Provide aliases for your sites. These will be used in place of your site id when generating paths throughout the application.
        siteAliases: {
            // RefArch: 'us'
            // RefArchGlobal: 'global'
        },
        // The sites for your app, which is imported from sites.js
        sites,
        // Commerce api config
        commerceAPI: {
            proxyPath: '/mobify/proxy/api',
            parameters: {
                clientId: dw.CLIENT_ID,
                organizationId: dw.ORGANIZATION_ID,
                shortCode: dw.SHORT_CODE,
                siteId: dw.SITE_ID
            }
        },
        // Einstein api config
        einsteinAPI: {
            host: 'https://api.cquotient.com',
            einsteinId: dw.EINSTEIN_ID,
            siteId: dw.EINSTEIN_SITE_ID,
            // Flag Einstein activities as coming from a production environment.
            // By setting this to true, the Einstein activities generated by the environment will appear
            // in production environment reports
            isProduction: dw.EINSTEIN_IS_PRODUCTION
        }
    },
    // This list contains server-side only libraries that you don't want to be compiled by webpack
    externals: [],
    // Page not found url for your app
    pageNotFoundURL: '/page-not-found',
    // Enables or disables building the files necessary for server-side rendering.
    ssrEnabled: true,
    // This list determines which files are available exclusively to the server-side rendering system
    // and are not available through the /mobify/bundle/ path.
    ssrOnly: ['ssr.js', 'ssr.js.map', 'node_modules/**/*.*'],
    // This list determines which files are available to the server-side rendering system
    // and available through the /mobify/bundle/ path.
    ssrShared: [
        'static/ico/favicon.ico',
        'static/robots.txt',
        '**/*.js',
        '**/*.js.map',
        '**/*.json'
    ],
    // Additional parameters that configure Express app behavior.
    ssrParameters: {
        ssrFunctionNodeVersion: '18.x',
        proxyConfigs: [
            {
                host: dw.API_COMMERCE_CLOUD,
                path: 'api'
            },
            {
                host: dw.DX_COMMERCE_CLOUD,
                path: 'ocapi'
            }
        ]
    }
}
